name: Build iOS Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Đã nâng cấp lên v4 tại đây

      - name: Setup Theos Action
        uses: Randomblock1/theos-action@v1
        with:
          theos-src: 'https://github.com/theos/theos'

      - name: Build Tweak
        run: |
          export THEOS=$GITHUB_WORKSPACE/theos
          make package FINALPACKAGE=1

      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v4  # Đã nâng cấp lên v4 tại đây
        with:
          name: CuongBypass-Dylib
          path: .theos/obj/debug/CuongBypass.dylib
